[project]
name = "gen-ai-pgp-term3-jio"
version = "0.1.0"
description = "Generative AI coursework - Jio Institute PGP AI & DS, Term 4"
readme = "README.md"
authors = [
    { name = "Kushagra Gupta", email = "aakg2310@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "langchain>=1.4.0",
    "langchain-core>=1.6.3",
    "langchain-groq>=1.1.3",
    "langchain-ollama>=1.1.0",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "tqdm>=4.70.1",
]
